### ISSUE TITLE
separate the code

### ISSUE THREAD

**Issue by PkayJava** [BSVogler/WurfelEngineSDK#13]
It would be good to separate code for like libgdx project.
- desktop
- android

**Comment by BSVogler** [comment]
Do you mean like libGDX Projects are usually separated? I don't know if this runs on android without modification so before attempting this the android build should be tested. I know that Android has smaller limits on maximum texture size and wurfel engine uses quite huge textures.

**Comment by PkayJava** [comment]
Yeah, but I am not quite sure also, but minecraft could run on android. your engine should not be a problem. if you could downgrade the code from 1.8 to 1.6, it would be much better.

**Comment by BSVogler** [comment]
Downgrade won't happen.
I created #14 for the android issue. If this works changing the directory structure  may be worth considering.

**Comment by PkayJava** [comment]
If I help to downgrade the api to java 1.6, does sound ok to you ?

**Comment by BSVogler** [comment]
I don't see any reasons to downgrade the code to a 11 year old technology. I know that there are versions of Mac OS where the JVM cannot be upgraded but these are usually not devices used to play games. You can always develop your own fork if you still need it for whatever reason.

**Comment by PkayJava** [comment]
android old version is still using 1.6 api.
